### ISSUE TITLE
Add Project (and Milestone)

### ISSUE THREAD

**Issue by VaclavElias** [VaclavElias/Emsi#13]
- [x] Add new project, name it e.g. Emsi Workflow and select the right project for us
- [x] Add issues to the project
- [x] Add milestone e.g.  v1.0, v2.0 assign all issues to this milestone (we can split issues to multiple milestones)
- [x] Let the team know about the Project in any upcoming catch up

https://github.com/VaclavElias/Emsi/projects

Github Project vs Milestone
https://stackoverflow.com/questions/39591795/what-is-the-difference-relationship-between-github-projects-and-milestones
